# Generated by Django 5.0.7 on 2024-08-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('regions', models.TextField(default='1,2')),
                ('crystal_structure', models.CharField(choices=[('diamond', 'diamond'), ('zincblende', 'zincblende'), ('simplecubic', 'simplecubic'), ('wurtzite', 'wurtzite'), ('hexagonal', 'hexagonal'), ('Bi2Te3', 'Bi2Te3'), ('graphene', 'graphene'), ('CNT', 'CNT'), ('buckyball', 'buckyball'), ('bcc', 'bcc'), ('caesiumchloride', 'caesiumchloride'), ('sodiumchloride', 'sodiumchloride'), ('tetragonal', 'tetragonal'), ('tetragonalI', 'tetragonaLI'), ('orthorhombic', 'orthorhombic'), ('orthorhombicC', 'orthorhombicC'), ('orthorhombicF', 'orthorhombicF'), ('orthorhombicI', 'orthorhombicI'), ('monoclinic', 'monoclinic'), ('monoclinicC', 'monoclinicC'), ('triclinic', 'triclinic')], max_length=100)),
                ('doping_type', models.CharField(blank=True, choices=[('N', 'N'), ('P', 'P')], max_length=100, null=True)),
                ('doping_density', models.FloatField(blank=True, null=True)),
                ('charge_model', models.CharField(blank=True, choices=[('electron_core', 'electron_core'), ('electron_hole', 'electron_hole')], max_length=100, null=True)),
                ('doping_ionization_model', models.CharField(blank=True, choices=[('full_ionization', 'full_ionization'), ('thermal_ionization', 'thermal_ionization')], max_length=100, null=True)),
                ('doping_temperature', models.FloatField(blank=True, null=True)),
                ('ionization_energy', models.FloatField(blank=True, null=True)),
                ('doping_degeneracy', models.FloatField(blank=True, null=True)),
                ('nanotube_indices', models.JSONField(blank=True, null=True)),
                ('disorder_type', models.CharField(blank=True, choices=[('totally_random_dopant', 'totally_random_dopant'), ('ordered_dopant', 'ordered_dopant')], max_length=100, null=True)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('polarization', models.JSONField(blank=True, null=True)),
                ('strain_simulation', models.BooleanField(default=False)),
                ('is_alloy', models.BooleanField(default=False)),
                ('mole_fraction', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
