# Generated by Django 5.0.7 on 2024-08-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emschrodingerfem',
            name='active_regions',
        ),
        migrations.RemoveField(
            model_name='nonlinearpoissonfem',
            name='active_regions',
        ),
        migrations.RemoveField(
            model_name='semiclassicalfem',
            name='active_regions',
        ),
        migrations.CreateModel(
            name='ActiveRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solver_object_id', models.PositiveIntegerField()),
                ('region_object_id', models.PositiveIntegerField()),
                ('region_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_active_regions', to='contenttypes.contenttype')),
                ('solver_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_active_regions', to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('solver_content_type', 'solver_object_id', 'region_content_type', 'region_object_id')},
            },
        ),
    ]
