# Generated by Django 5.0.7 on 2024-08-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_boundaryregion_shape_alter_region_shape'),
        ('solver', '0002_remove_emschrodingerfem_active_regions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emschrodingerfem',
            name='active_regions',
            field=models.ManyToManyField(blank=True, to='regions.region'),
        ),
        migrations.AddField(
            model_name='nonlinearpoissonfem',
            name='active_regions',
            field=models.ManyToManyField(blank=True, to='regions.region'),
        ),
        migrations.AddField(
            model_name='semiclassicalfem',
            name='active_regions',
            field=models.ManyToManyField(blank=True, to='regions.region'),
        ),
        migrations.DeleteModel(
            name='ActiveRegion',
        ),
    ]
