# Generated by Django 5.0.7 on 2024-08-14 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('Cuboid', 'Cuboid'), ('Spheroid', 'Spheroid'), ('Pyramid', 'Pyramid'), ('Cylinder', 'Cylinder'), ('Dome', 'Dome')], max_length=10)),
                ('tag', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_tag', message='Tag must be alphanumeric.', regex='^[A-Za-z0-9]+$')])),
                ('region_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('min_x', models.FloatField()),
                ('min_y', models.FloatField()),
                ('min_z', models.FloatField()),
                ('max_x', models.FloatField()),
                ('max_y', models.FloatField()),
                ('max_z', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.CheckConstraint(check=models.Q(('region_number__gte', 1)), name='region_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 1)), name='priority_gte_1'),
        ),
    ]
