# Generated by Django 5.0.7 on 2024-08-14 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('Cuboid', 'Cuboid'), ('Spheroid', 'Spheroid'), ('Pyramid', 'Pyramid'), ('Cylinder', 'Cylinder'), ('Dome', 'Dome')], max_length=10)),
                ('tag', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_tag', message='Tag must be alphanumeric.', regex='^[A-Za-z0-9]+$')])),
                ('region_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('work_plane', models.CharField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1)),
                ('plane_tolerance', models.FloatField()),
                ('axis_cut', models.IntegerField()),
                ('rectangles', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
