# Generated by Django 5.0.7 on 2024-08-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_boundaryregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundaryregion',
            name='shape',
            field=models.CharField(choices=[('Cuboid', 'Cuboid'), ('Spheroid', 'Spheroid'), ('Pyramid', 'Pyramid'), ('Cylinder', 'Cylinder'), ('Dome', 'Dome'), ('2d', '2d')], max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='shape',
            field=models.CharField(choices=[('Cuboid', 'Cuboid'), ('Spheroid', 'Spheroid'), ('Pyramid', 'Pyramid'), ('Cylinder', 'Cylinder'), ('Dome', 'Dome'), ('2d', '2d')], max_length=10),
        ),
    ]
