# Generated by Django 5.0.7 on 2024-08-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0002_remove_boundarycondition_solver_name_and_more'),
        ('materials', '0001_initial'),
        ('regions', '0003_alter_boundaryregion_shape_alter_region_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundarycondition',
            name='boundary_regions',
        ),
        migrations.RemoveField(
            model_name='boundarycondition',
            name='semiconductor',
        ),
        migrations.RemoveField(
            model_name='boundarycondition',
            name='surface_of_regions',
        ),
        migrations.AddField(
            model_name='boundarycondition',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='boundary_conditions', to='regions.region'),
        ),
        migrations.AddField(
            model_name='boundarycondition',
            name='semiconductor_materials',
            field=models.ManyToManyField(blank=True, related_name='boundary_conditions', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='boundarycondition',
            name='single_surface_normal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
