# Generated by Django 5.0.7 on 2024-08-15 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0004_remove_boundarycondition_regions_and_more'),
        ('materials', '0001_initial'),
        ('regions', '0003_alter_boundaryregion_shape_alter_region_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundarycondition',
            name='boundary_regions',
        ),
        migrations.AlterField(
            model_name='boundarycondition',
            name='semiconductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schottky_contacts', to='materials.material'),
        ),
        migrations.AddField(
            model_name='boundarycondition',
            name='boundary_regions',
            field=models.ManyToManyField(blank=True, related_name='electrostatic_contacts', to='regions.region'),
        ),
    ]
