# Generated by Django 5.0.7 on 2024-08-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0005_remove_boundarycondition_boundary_regions_and_more'),
        ('regions', '0003_alter_boundaryregion_shape_alter_region_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundarycondition',
            name='boundary_regions',
            field=models.ManyToManyField(blank=True, related_name='boundary_conditions', to='regions.region'),
        ),
    ]
