# Generated by Django 5.0.7 on 2024-08-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0006_alter_boundarycondition_boundary_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundarycondition',
            name='solver_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
