# Generated by Django 5.0.7 on 2024-08-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0007_boundarycondition_solver_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundarycondition',
            options={'verbose_name': 'Boundary Condition', 'verbose_name_plural': 'Boundary Conditions'},
        ),
        migrations.RemoveField(
            model_name='boundarycondition',
            name='E_field',
        ),
        migrations.RemoveField(
            model_name='boundarycondition',
            name='potential_simulation',
        ),
        migrations.RemoveField(
            model_name='boundarycondition',
            name='solver_name',
        ),
        migrations.AlterField(
            model_name='boundarycondition',
            name='semiconductor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boundarycondition',
            name='single_surface_normal',
            field=models.CharField(default='1,0,0', max_length=20),
        ),
        migrations.AlterField(
            model_name='boundarycondition',
            name='surface_of_regions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boundarycondition',
            name='type',
            field=models.CharField(choices=[('ElectrostaticContact', 'Electrostatic Contact'), ('SchottkyContact', 'Schottky Contact')], max_length=50),
        ),
    ]
