# Generated by Django 5.0.7 on 2024-08-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary', '0009_remove_boundarycondition_boundary_regions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundarycondition',
            name='solver_model_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
