# Generated by Django 5.0.7 on 2024-08-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_type',
            field=models.CharField(default='FEM_macroscopic', help_text="The type of domain, defaults to 'FEM_macroscopic' for finite element method.", max_length=100),
        ),
    ]
